name: OKEGui Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Clone & Build eac3to-wrapper
      shell: bash
      run: |
        git clone https://github.com/AkarinVS/eac3to-wrapper
        cd eac3to-wrapper
        go build -ldflags "-X main.version=$(git describe --tags)"
        cd ..

    - name: Restore Packages
      run: nuget restore OKEGui/OKEGui.sln

    - name: Build Solution
      run: |
        msbuild.exe OKEGui/OKEGui.sln /nologo /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"

    - name: Integrate eac3to-wrapper
      shell: bash
      run: |
        mkdir -p "./OKEGui/OKEGui/bin/Release/tools/eac3to"
        cp eac3to-wrapper/eac3to-wrapper.exe "./OKEGui/OKEGui/bin/Release/tools/eac3to"

    - name: Package release
      shell: bash
      run: |
        cd "./OKEGui/OKEGui/bin/"
        mv Release "OKEGui-Amod-$(git describe --tags)"
        git clone https://github.com/AkarinVS/zip/
        zip/zip.exe -9r amd64.zip "OKEGui-Amod-$(git describe --tags)"/

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "./OKEGui/OKEGui/bin/amd64.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
