name: OKEGui Mod Release

on:
  push:
    tags: v*
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    #if: github.event.base_ref == 'refs/heads/mod'

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Clone & Build eac3to-wrapper
      shell: bash
      run: |
        git clone https://github.com/AkarinVS/eac3to-wrapper
        cd eac3to-wrapper
        go build -ldflags "-X main.version=$(git describe --tags)"
        cd ..

    - name: Restore Packages
      run: nuget restore OKEGui/OKEGui.sln

    - name: Build Solution
      run: |
        msbuild.exe OKEGui/OKEGui.sln /nologo /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"

    - name: Integrate eac3to-wrapper
      shell: bash
      run: |
        mkdir -p "./OKEGui/OKEGui/bin/Release/tools/eac3to"
        cp eac3to-wrapper/eac3to-wrapper.exe "./OKEGui/OKEGui/bin/Release/tools/eac3to"

    - name: Package release
      shell: bash
      run: |
        git clone https://github.com/AkarinVS/exe
        export PATH=`pwd`/exe/:$PATH
        pushd ./OKEGui/OKEGui/bin
        zip -9r ../../../"OKEGui-mod-$(git describe --tags).zip" Release

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: OKEGui-*.zip
        body_path: RELNOTES.md
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
